name: Deploy
on:
  push:
  workflow_dispatch:
    inputs:
      deploy_trigger_source:
        default: "github"

jobs:
  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "www"
    steps:
      - uses: actions/checkout@v3

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-comment: false
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          alias-domains: chinatownjs-sanctucompu.vercel.app
          working-directory: "www"